### ISSUE TITLE
Creation of a pop up which will open when click on system in sidebar 

### ISSUE THREAD

**Issue by Ashmitkumar1** [Ashmitkumar1/Firewall--Admin--Panel#10]
Need for the creation of a popup which will open when any user click on system in sidebar 
Can leave the red marked area except that yu need to create the whole popup 

![image](https://github.com/user-attachments/assets/414d93e2-962c-4dd8-8c74-d4871be502af)

**Comment by prayag78** [comment]
Hello @Ashmitkumar1 , 
I'd love to contribute to this issue .

**Comment by Ashmitkumar1** [comment]
@prayag78 Sure go ahead and please use tailwind css for designing
