### ISSUE TITLE
Creation of web services UI component 

### ISSUE THREAD

**Issue by Ashmitkumar1** [Ashmitkumar1/Firewall--Admin--Panel#12]
This UI will be visible when user clicks on web services dropdown in the sidebar and then under website section 
You need to create a web services UI section as shown in the image 
Can use dummy data 
Create the design similar to the image 

![image](https://github.com/user-attachments/assets/4e2a4dd4-b60d-447e-9141-a2fcd20308ac)

**Comment by Ashu1823** [comment]
Hi @Ashmitkumar1 this issue also handled in my PR but this needs some enhancement. Can you please assign this one to work on it.

**Comment by Ashmitkumar1** [comment]
@Ashu1823  Sure bro
