### ISSUE TITLE
Creation of  Dashboard  Ui for Basic button 

### ISSUE THREAD

**Issue by Ashmitkumar1** [Ashmitkumar1/Firewall--Admin--Panel#13]
Need to create the header of the dashboard which as shown in the image which will be visible when user clicks on basic 

![image](https://github.com/user-attachments/assets/852aa4d7-38e8-4c99-94e7-aaf66243d2de)

**Comment by AADESHak007** [comment]
@Ashmitkumar1 I would like to work on this issue .
Do you want similar page for the basic button?

**Comment by Ashmitkumar1** [comment]
@AADESHak007 Sure Go Ahead 
Yes i want similar page

**Comment by AADESHak007** [comment]
Okay and thanks

**Comment by Ashmitkumar1** [comment]
@AADESHak007 Hlo bro any update ?

**Comment by AADESHak007** [comment]
@Ashmitkumar1  yeah  I am working on it . I ll raise a PR till saturday for sure

**Comment by Ashmitkumar1** [comment]
Ok Bro
