### ISSUE TITLE
Creation of sidebar for Main page 

### ISSUE THREAD

**Issue by Ashmitkumar1** [Ashmitkumar1/Firewall--Admin--Panel#2]
Have to create a seperate component and create only sidebar for now .

![image](https://github.com/user-attachments/assets/4a91f762-bcd1-4f6c-af5a-427840dbd0bb)

**Comment by namansharma3007** [comment]
Can you assign this issue to me. I can build this.

**Comment by namansharma3007** [comment]
Hey @Ashmitkumar1  can you please add hacktoberfest-accepted label to this issue so that it gets accepted.

**Comment by Ashmitkumar1** [comment]
@Ashmitkumar1 done bro
