### ISSUE TITLE
Creation of a datatable 

### ISSUE THREAD

**Issue by Ashmitkumar1** [Ashmitkumar1/Firewall--Admin--Panel#4]
Create a new Component homepage
Your task is to create a  Frontend UI using jsx and react icons in react 
Which looks like this 

![image](https://github.com/user-attachments/assets/5e84103d-d2bc-4c93-bfa1-115846f0e068)

**Comment by Ashu1823** [comment]
Hi..
Can you please assign this one to me.

**Comment by Ashmitkumar1** [comment]
@Ashu1823 You can start working on it

**Comment by Ashu1823** [comment]
Hi thanks for assigning.. is there any UX file that I can refer to.

**Comment by Ashmitkumar1** [comment]
@Ashu1823  Unfortunately for now i don't have file but  you can refer this image
You can design it according to you but make sure it contains dummy information 
![image](https://github.com/user-attachments/assets/27a4a473-d666-4c2d-928f-778bb1ff5b67)

**Comment by Ashu1823** [comment]
Okay @Ashmitkumar1 fine..

**Comment by namansharma3007** [comment]
I already have added the required colors in the tailwind.config.js file please refer that.
Please add custom colors in that file for better development purposes.

**Comment by Ashu1823** [comment]
Hi @Ashmitkumar1  I have some doubts.. Can we have a meeting for clarifications.

**Comment by Ashmitkumar1** [comment]
@Ashu1823 bro i am busy with my placements session  sorry for that .
Can you please describe your issue i will surely clear your doubts

**Comment by Ashu1823** [comment]
Its fine @Ashmitkumar1 .
My doubts are:
1. the advance details of the tables are buttons?
2. end of each row has one icon, can you please explain the use of that icon.
3.  can you please explain the usage of the add site button (like what are the coonfigutaions to show)
4. on which side bar selection I will show this table view?

**Comment by Ashmitkumar1** [comment]
Ok bro @Ashu1823 
1.  Its a simple div or p element with some designing you can also use buttons if you want 
2. Its is use to open more option in the small pop which opens just right below corner of the row But you don't need to implement that just place that icon 
3. You can leave the functionality part just add button Because the firewall is not ready yet .
4. Under Sites section on the sidebar

**Comment by Ashu1823** [comment]
Thanks @Ashmitkumar1 Bro.

**Comment by Ashu1823** [comment]
Hi @Ashmitkumar1 Completed and Raised PR for this ticket.  Please review and merge.
![image](https://github.com/user-attachments/assets/7fa414ee-f96c-4bc7-be8e-413749a00c35)

**Comment by Ashu1823** [comment]
Also @Ashmitkumar1 the issue no #12 also added like according to the route the pages will load. But some enhancement is required in that issue.
