### ISSUE TITLE
UI for dashboard 

### ISSUE THREAD

**Issue by Ashmitkumar1** [Ashmitkumar1/Firewall--Admin--Panel#6]
Create an UI for the marked area .
You can design it according to you but must contains all details section with dummy data 

![image](https://github.com/user-attachments/assets/3d9a5230-b64a-4feb-bc5a-5f7b0b24a271)

**Comment by haseebzaki-07** [comment]
Hey @Ashmitkumar1 , I can design the UI similar to the one u want. Please assign me this issue and I will complete it in required time.

**Comment by Ashmitkumar1** [comment]
@haseebzaki-07  sure go ahead
