### ISSUE TITLE
Creation Of Dashboard Component 

### ISSUE THREAD

**Issue by Ashmitkumar1** [Ashmitkumar1/Firewall--Admin--Panel#8]
Your task is to create the UI as marked under red rectangle 
For colored lines you can configure the div by setting its height and width please don't use images
Place this component below the Dashboard UI section 

![image](https://github.com/user-attachments/assets/3785f032-9d7c-4113-94fe-1a4ea85cd565)

**Comment by Chetan8299** [comment]
Hi @Ashmitkumar1  can you assign this issue to me.

**Comment by Ashmitkumar1** [comment]
@Chetan8299  Sure go ahead Please use tailwind for designing
